on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 15 * *'
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
          # - beta
          # - nightly
        os:
          # - macos-latest
          # - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: install socat
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install socat -y
          socat -V
      - name: install socat
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install socat
          socat -V
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ runner.os == 'Windows' }}
      - name: install com0com
        if: ${{ runner.os == 'Windows' }}
        run: |
          CertMgr.exe /add com0com.cer /s /r localMachine root
          CertMgr.exe /add com0com.cer /s /r localMachine trustedpublisher
          .\setup_com0com_W7_x64_signed.exe /S
        working-directory: .github
      - name: setup com0com
        if: ${{ runner.os == 'Windows' }}
        run: .\setupc.exe install PortName=COM10,EmuBR=yes PortName=COM11,EmuBR=yes
        working-directory: C:\Program Files (x86)\com0com
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -j1 -- --test-threads=1
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
